import { precacheAndRoute } from 'workbox-precaching';
import { CacheFirst, NetworkFirst, NetworkOnly } from 'workbox-strategies';
import { registerRoute } from 'workbox-routing';

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Cache First for static assets
registerRoute(
  ({ request }) => request.destination === 'style' || request.destination === 'script',
  new CacheFirst({
    cacheName: 'static-assets',
  })
);

// Network First for API calls (healthz, version)
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/v1/'),
  new NetworkFirst({
    cacheName: 'api-cache',
  })
);

// Network Only for WebSocket
registerRoute(
  ({ url }) => url.pathname === '/api/v1/ws',
  new NetworkOnly()
);
