import { precacheAndRoute } from 'workbox-precaching';
import { CacheFirst, NetworkFirst, NetworkOnly } from 'workbox-strategies';
import { registerRoute } from 'workbox-routing';
import { saveEvent } from './cache-strategy';

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Cache First for static assets
registerRoute(
  ({ request }) => request.destination === 'style' || request.destination === 'script',
  new CacheFirst({
    cacheName: 'static-assets',
  })
);

// Network First for API calls (healthz, version)
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/v1/'),
  new NetworkFirst({
    cacheName: 'api-cache',
  })
);

// Network Only for WebSocket
registerRoute(
  ({ url }) => url.pathname === '/api/v1/ws',
  new NetworkOnly()
);

// Listen for WebSocket messages and save to IndexedDB
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'WS_EVENT') {
    saveEvent(event.data.payload);
  }
});
